vich_uploader:
    db_driver: orm

    mappings:
        motif_pdf:
            uri_prefix: /motifPDF
            upload_destination: '%kernel.project_dir%/public/uploads/motifPDF/'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        personnel_image:
            uri_prefix: /images/personnels
            upload_destination: '%kernel.project_dir%/public/uploads/images/personnels'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        parametre_image:
            uri_prefix: /images/parametres
            upload_destination: '%kernel.project_dir%/public/uploads/images/parametres'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

